sudo: required

services:
  - docker

script:
- docker-compose up -d
- docker ps -a
- docker exec thegamblingclubpokerleague_php_1 ls
- docker exec thegamblingclubpokerleague_php_1 composer install --prefer-dist --no-scripts --no-progress --no-suggest
- docker exec thegamblingclubpokerleague_php_1 ls
- docker exec thegamblingclubpokerleague_php_1 ./vendor/phpunit/phpunit/phpunit