sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_8d86476699e6_key -iv $encrypted_8d86476699e6_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar

script:
- echo "Installing docker machine"
- "./bin/install-production-docker-machine.sh"
- npm install -g machine-share
- machine-import vm01.zip
- echo "Deploying to prod"
- export GOOGLE_APPLICATION_CREDENTIALS=google-cloud-auth.json
- docker-machine ls
- docker-machine --help
- ls /home/travis/.docker/machine
- docker-machine env vm01
- eval $(docker-machine env vm01)
- docker-machine ls
