sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_8d86476699e6_key -iv $encrypted_8d86476699e6_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
script:
- echo "Installing docker machine"
- "./bin/install-production-docker-machine.sh"
- "./bin/docker-machine-import.sh vm01.zip"
- echo "Deploying to prod"
- docker-machine ls