version: '2'

services:
    nginx:
        build:
            dockerfile: ./docker/nginx/Dockerfile
            context: ./
        ports:
            - "80:80"
        #volumes:
        #    - .:/var/www/html
    php:
        build:
            dockerfile: ./docker/php/Dockerfile
            context: ./
        volumes:
            - app_data:/var/www/html/var/data
volumes:
    app_data: {}