version: '2'

services:
    php:
        build:
            dockerfile: ./docker/apache/Dockerfile
            context: ./
        ports:
            - "80:80"
        volumes:
            - db-data:/var/www/html/var/data
        environment:
            HIDE_APP_DEV: 1
#    redis:
#        image: redis
#        depends_on:
#            - php
volumes:
    db-data:
