version: '2'

services:
    php:
        build:
            dockerfile: ./docker/apache/Dockerfile
            context: ./
        volumes:
            - .:/var/www/html:cached
        ports:
            - "8081:80"
#    redis:
#        image: redis
#        depends_on:
#            - php
    encore:
        image: node:10-alpine
        volumes:
            - .:/app
        working_dir: /app
        command: sh -c "yarn install && yarn encore dev"
