<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Player;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getLeagueTable()
    {
        return $this->getTableQueryBuilder()
            ->addSelect('SUM(results.leaguePoints) AS leaguePoints')
            ->andWhere('game.isLeague = 1')
            ->andWhere('player.leaguePlayer = 1')
            ->getQuery()
            ->getResult();
    }

    protected function getTableQueryBuilder(): QueryBuilder
    {
        return $this->createQueryBuilder('game')
            ->select('player.name, player.id AS playerId')
            ->addSelect('SUM(results.winnings) AS winnings')
            ->addSelect('SUM(results.noOfRebuys) AS noOfRebuys')
            ->addSelect('SUM((results.noOfRebuys + 1)*game.buyIn + results.addOn) AS boughtIn')
            ->innerJoin('game.results', 'results')
            ->leftJoin('results.player', 'player')
            ->groupBy('player.id');
    }

    public function getAllStatsTable()
    {
        return $this->getTableQueryBuilder()
            ->getQuery()
            ->getResult();
    }

    public function getAllHostGames(Player $host)
    {
        return $this->createQueryBuilder('game')
            ->andWhere('game.host = :host')
            ->setParameter('host', $host)
            ->getQuery()
            ->getResult();
    }
}
