<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Player;
use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function getGamesPlayed(Player $player)
    {
        return $this->createQueryBuilder('player')
            ->leftJoin('player', 'result');
    }

    public function findAllLeaguePlayers()
    {
        return $this->findBy(['leaguePlayer' => true]);
    }
}
