<?php

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * ResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRepository extends EntityRepository
{

    public function getLastUpdated()
    {
        return $this->createQueryBuilder('r')
            ->select('r.updatedAt')
            ->orderBy('r.updatedAt', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult();
    }
}
